name: Main

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unit-tests.yml

  integration-tests:
    name: Integration Tests
    uses: ./.github/workflows/integration-tests.yml
    needs: unit-tests